#!/bin/sh
# AmneziaWG Toggle Script - Hybrid (Static List + Domain Sniffing + 2026 MLBB Ports)

# --- Original Configuration ---
AWG_DIR="/data/usr/app/awg"
CFG="$AWG_DIR/amnezia_for_awg.conf"
IFCFG="$AWG_DIR/awg0.conf"
TOOLS_BIN="$AWG_DIR/awg"
AWG_GO="$AWG_DIR/amneziawg-go"
WATCHDOG_SCRIPT="$AWG_DIR/awg_watchdog.sh"
LAN_NET="192.168.31.0/24"
LAN_BR="br-lan"
STATE_FILE="/tmp/awg_wan_state"

# --- Split Routing Config (YouTube) ---
IPSET_NAME="youtube"
WAN_TABLE="200"
FW_MARK="0x200"
YT_URL="https://raw.githubusercontent.com/touhidurrr/iplist-youtube/main/lists/ipv4.txt"
YT_CACHE="$AWG_DIR/youtube_ipv4.txt"
YT_DOMAINS="youtube.com youtu.be music.youtube.com googlevideo.com ytimg.com ggpht.com googleusercontent.com gvt1.com gvt2.com"

# --- Split Routing Config (Mobile Legends 2026) ---
ML_IPSET="mobile_legends"
ML_CACHE="$AWG_DIR/mobile_legends_ipv4.txt"
ML_DOMAINS="mobilelegends.com moonton.com youngjoygame.com akamaihd.net unity3d.com"
# Updated 2026 Port Ranges for Battle Data and regional GGS relays
ML_TCP_PORTS="5000:5241,5551:5700,9001,9443,30000:30300"
ML_UDP_PORTS="4001:4009,5000:5500,8000:8100,10000:15000,20000:30300"

DNS_CONF_DIR="/etc/dnsmasq.d"
DNS_CONF_FILE="$DNS_CONF_DIR/awg_split_tunnel.conf"

die()   { echo "Error: $*" >&2; exit 1; }
root()  { [ "$(id -u)" -eq 0 ] || die "Run as root"; }

# --- Helper: Save/Load MLBB IP Cache ---
save_ml_ips() {
    echo "Saving Mobile Legends IPs to $ML_CACHE..."
    if ipset list "$ML_IPSET" >/dev/null 2>&1; then
        # Extracts only the IP addresses from the ipset list
        ipset list "$ML_IPSET" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' > "$ML_CACHE"
    fi
}

load_ml_ips() {
    ipset create "$ML_IPSET" hash:net maxelem 100000 2>/dev/null || true
    if [ -s "$ML_CACHE" ]; then
        echo "Restoring MLBB IPs from cache..."
        sed "s/^/add $ML_IPSET /" "$ML_CACHE" | ipset restore -! 2>/dev/null
    fi
}

# --- Helper: WAN Management (Original Logic) ---
save_wan_info() {
    ROUTE_INFO=$(ip route get 1.1.1.1 2>/dev/null | head -n 1)
    GW=$(echo "$ROUTE_INFO" | awk '{ for(i=1; i<=NF; i++) if ($i=="via") print $(i+1) }')
    IF=$(echo "$ROUTE_INFO" | awk '{ for(i=1; i<=NF; i++) if ($i=="dev") print $(i+1) }')

    if [ "$IF" = "awg0" ]; then
        return 1
    fi

    if [ -n "$GW" ] && [ -n "$IF" ]; then
        echo "$GW $IF" > "$STATE_FILE"
        return 0
    else
        return 1
    fi
}

get_saved_wan() {
    if [ -f "$STATE_FILE" ]; then
        WAN_GW=$(awk '{print $1}' "$STATE_FILE")
        WAN_IF=$(awk '{print $2}' "$STATE_FILE")
    else
        return 1
    fi
}

# --- DNS & IPSet Loading ---
setup_dns_ipset() {
    [ -d "$DNS_CONF_DIR" ] || mkdir -p "$DNS_CONF_DIR"
    echo "# Auto-generated by AWG Script" > "$DNS_CONF_FILE"
    for domain in $YT_DOMAINS; do echo "ipset=/$domain/$IPSET_NAME" >> "$DNS_CONF_FILE"; done
    for domain in $ML_DOMAINS; do echo "ipset=/$domain/$ML_IPSET" >> "$DNS_CONF_FILE"; done
    /etc/init.d/dnsmasq restart
}

load_youtube_ips() {
    ipset create "$IPSET_NAME" hash:net maxelem 100000 2>/dev/null || true
    if [ ! -s "$YT_CACHE" ]; then
        curl -s --connect-timeout 10 "$YT_URL" -o "$YT_CACHE"
    fi
    if [ -s "$YT_CACHE" ]; then
        ipset flush "$IPSET_NAME"
        sed "s/^/add $IPSET_NAME /" "$YT_CACHE" | ipset restore -!
    fi
}

# --- Firewall Logic ---
apply_fw() {
    # Forwarding (Original Config)
    iptables -C FORWARD -i "$LAN_BR" -o awg0 -j ACCEPT 2>/dev/null || iptables -A FORWARD -i "$LAN_BR" -o awg0 -j ACCEPT
    iptables -C FORWARD -i awg0 -o "$LAN_BR" -j ACCEPT 2>/dev/null || iptables -A FORWARD -i awg0 -o "$LAN_BR" -j ACCEPT
    iptables -t nat -C POSTROUTING -s "$LAN_NET" -o awg0 -j MASQUERADE 2>/dev/null || iptables -t nat -A POSTROUTING -s "$LAN_NET" -o awg0 -j MASQUERADE

    # Routing Table Setup
    ip route flush table "$WAN_TABLE"
    ip route add default via "$WAN_GW" dev "$WAN_IF" table "$WAN_TABLE"
    ip rule del fwmark "$FW_MARK" table "$WAN_TABLE" 2>/dev/null
    ip rule add fwmark "$FW_MARK" table "$WAN_TABLE"

    # Mangle Rules (YouTube + MLBB IPset)
    iptables -t mangle -A PREROUTING -m set --match-set "$IPSET_NAME" dst -j MARK --set-mark "$FW_MARK"
    iptables -t mangle -A PREROUTING -m set --match-set "$ML_IPSET" dst -j MARK --set-mark "$FW_MARK"

    # Mangle Rules (MLBB 2026 Ports)
    iptables -t mangle -A PREROUTING -p tcp -m multiport --dports "$ML_TCP_PORTS" -j MARK --set-mark "$FW_MARK"
    iptables -t mangle -A PREROUTING -p udp -m multiport --dports "$ML_UDP_PORTS" -j MARK --set-mark "$FW_MARK"

    # Local Router Output Marking
    iptables -t mangle -A OUTPUT -m set --match-set "$IPSET_NAME" dst -j MARK --set-mark "$FW_MARK"
    iptables -t mangle -A OUTPUT -m set --match-set "$ML_IPSET" dst -j MARK --set-mark "$FW_MARK"
}

remove_fw() {
    iptables -t mangle -F PREROUTING 2>/dev/null
    iptables -t mangle -F OUTPUT 2>/dev/null
    ip rule del fwmark "$FW_MARK" table "$WAN_TABLE" 2>/dev/null
    ip route flush table "$WAN_TABLE" 2>/dev/null
}

# --- Control Functions ---
up() {
    root
    if ip link show awg0 >/dev/null 2>&1; then echo "VPN is already UP"; exit 0; fi

    save_wan_info || die "Could not detect WAN"
    get_saved_wan

    WG_SERVER=$(grep "^Endpoint" "$CFG" | sed 's/.*= *//' | cut -d':' -f1 | tr -d '\r')
    WG_ADDR=$(awk -F' = ' '/^Address/ {print $2}' "$CFG" | cut -d',' -f1 | tr -d '\r')
    awk '!/^Address/ && !/^DNS/' "$CFG" > "$IFCFG"

    pkill -f amneziawg-go 2>/dev/null
    export WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD=1
    $AWG_GO awg0 >/dev/null 2>&1 &
    
    count=0
    while ! ip link show awg0 >/dev/null 2>&1; do
        sleep 0.5
        count=$((count+1))
        [ $count -ge 10 ] && die "awg0 failed"
    done

    ip addr add "$WG_ADDR" dev awg0
    "$TOOLS_BIN" setconf awg0 "$IFCFG"
    ip link set up awg0
    ip link set mtu 1280 dev awg0

    load_youtube_ips
    load_ml_ips
    setup_dns_ipset

    ip route add "$WG_SERVER"/32 via "$WAN_GW" dev "$WAN_IF"
    ip route del default 2>/dev/null
    ip route add default dev awg0

    remove_fw
    apply_fw
    /etc/init.d/firewall reload
    echo "VPN UP: YouTube & MLBB routed via WAN ($WAN_IF)"
}

down() {
    root
    save_ml_ips  # Automatically save discovered IPs before shutting down
    get_saved_wan
    WG_SERVER=$(grep "^Endpoint" "$CFG" | sed 's/.*= *//' | cut -d':' -f1 | tr -d '\r')

    ip route del default dev awg0 2>/dev/null
    [ -n "$WG_SERVER" ] && ip route del "$WG_SERVER"/32 2>/dev/null
    [ -n "$WAN_GW" ] && ip route add default via "$WAN_GW" dev "$WAN_IF" 2>/dev/null

    remove_fw
    if [ -f "$DNS_CONF_FILE" ]; then rm -f "$DNS_CONF_FILE"; /etc/init.d/dnsmasq restart; fi
    
    ip link del awg0 2>/dev/null
    pkill -f amneziawg-go 2>/dev/null
    rm -f "$STATE_FILE" "$IFCFG" 2>/dev/null
    /etc/init.d/firewall reload
    echo "VPN DOWN: MLBB IPs cached."
}

case "$1" in
    up) up ;;
    down) down ;;
    save) save_ml_ips ;;
    status) 
        if ip link show awg0 >/dev/null 2>&1; then
            echo "Status: CONNECTED"
            echo "MLBB IPs Cached: $(wc -l < $ML_CACHE 2>/dev/null || echo 0)"
        else
            echo "Status: DISCONNECTED"
        fi
        ;;
    restart) down; sleep 1; up ;;
    *) echo "Usage: $0 {up|down|save|status|restart}" ;;
esac
