#!/bin/sh
# AmneziaWG Toggle Script - Hybrid (Static List + Domain Sniffing)

# --- Configuration ---
AWG_DIR="/data/usr/app/awg"
CFG="$AWG_DIR/amnezia_for_awg.conf"
IFCFG="$AWG_DIR/awg0.conf"
TOOLS_BIN="$AWG_DIR/awg"
AWG_GO="$AWG_DIR/amneziawg-go"
WATCHDOG_SCRIPT="$AWG_DIR/awg_watchdog.sh"
LAN_NET="192.168.31.0/24"
LAN_BR="br-lan"
STATE_FILE="/tmp/awg_wan_state"

# --- Split Routing Config ---
IPSET_NAME="youtube"
WAN_TABLE="200"
FW_MARK="0x200"
YT_URL="https://raw.githubusercontent.com/touhidurrr/iplist-youtube/main/lists/ipv4.txt"
YT_CACHE="$AWG_DIR/youtube_ipv4.txt"

# --- NEW: Domain List for Dnsmasq ---
# These domains will be forced into the 'youtube' ipset when resolved
YT_DOMAINS="youtube.com youtu.be music.youtube.com googlevideo.com ytimg.com ggpht.com googleusercontent.com gvt1.com gvt2.com"
DNSMASQ_CONF_DIR="/etc/dnsmasq.d"
DNSMASQ_CONF_FILE="$DNSMASQ_CONF_DIR/awg_youtube.conf"

die()   { echo "Error: $*" >&2; exit 1; }
root()  { [ "$(id -u)" -eq 0 ] || die "Run as root"; }

# --- Helper: Detect and Save WAN Gateway ---
save_wan_info() {
    ROUTE_INFO=$(ip route get 1.1.1.1 2>/dev/null | head -n 1)
    GW=$(echo "$ROUTE_INFO" | awk '{ for(i=1; i<=NF; i++) if ($i=="via") print $(i+1) }')
    IF=$(echo "$ROUTE_INFO" | awk '{ for(i=1; i<=NF; i++) if ($i=="dev") print $(i+1) }')

    if [ "$IF" = "awg0" ]; then
        echo "Detected awg0 as WAN. VPN is likely already up. Skipping save."
        return 1
    fi

    if [ -n "$GW" ] && [ -n "$IF" ]; then
        echo "$GW $IF" > "$STATE_FILE"
        echo "Saved WAN State: Gateway $GW on $IF"
        return 0
    else
        echo "Failed to detect WAN gateway!"
        return 1
    fi
}

get_saved_wan() {
    if [ -f "$STATE_FILE" ]; then
        WAN_GW=$(awk '{print $1}' "$STATE_FILE")
        WAN_IF=$(awk '{print $2}' "$STATE_FILE")
    else
        return 1
    fi
}

# --- NEW: Configure Dnsmasq ---
setup_dns_ipset() {
    echo "Configuring dnsmasq to sniff YouTube domains..."
    
    # Ensure directory exists
    [ -d "$DNSMASQ_CONF_DIR" ] || mkdir -p "$DNSMASQ_CONF_DIR"

    # Create config file
    echo "# Auto-generated by AWG Script" > "$DNSMASQ_CONF_FILE"
    for domain in $YT_DOMAINS; do
        echo "ipset=/$domain/$IPSET_NAME" >> "$DNSMASQ_CONF_FILE"
    done

    # Restart dnsmasq to apply changes
    /etc/init.d/dnsmasq restart
    echo "Dnsmasq updated."
}

remove_dns_ipset() {
    if [ -f "$DNSMASQ_CONF_FILE" ]; then
        rm -f "$DNSMASQ_CONF_FILE"
        /etc/init.d/dnsmasq restart
        echo "Dnsmasq configuration removed."
    fi
}

# --- Existing: Bulk Load YouTube IPs ---
load_youtube_ips() {
    echo "Processing YouTube IP List..."
    
    # 1. Create IPSet (Maxelem increased to 100000 for large list)
    ipset create "$IPSET_NAME" hash:net maxelem 100000 comment 2>/dev/null || true
    
    # 2. Download list if not exists or empty
    if [ ! -s "$YT_CACHE" ]; then
        echo "Downloading IP list from GitHub..."
        curl -s --connect-timeout 10 "$YT_URL" -o "$YT_CACHE"
    fi

    if [ -s "$YT_CACHE" ]; then
        echo "Loading $(wc -l < "$YT_CACHE") IPs into set..."
        ipset flush "$IPSET_NAME"
        sed "s/^/add $IPSET_NAME /" "$YT_CACHE" | ipset restore -!
        echo "YouTube IP List Loaded."
    else
        echo "Warning: Could not find or download YouTube IP list."
    fi
}

apply_fw() {
    # VPN Forwarding
    iptables -C FORWARD -i "$LAN_BR" -o awg0 -j ACCEPT 2>/dev/null || iptables -A FORWARD -i "$LAN_BR" -o awg0 -j ACCEPT
    iptables -C FORWARD -i awg0 -o "$LAN_BR" -j ACCEPT 2>/dev/null || iptables -A FORWARD -i awg0 -o "$LAN_BR" -j ACCEPT
    iptables -C INPUT -i awg0 -j ACCEPT 2>/dev/null || iptables -A INPUT -i awg0 -j ACCEPT
    iptables -t nat -C POSTROUTING -s "$LAN_NET" -o awg0 -j MASQUERADE 2>/dev/null || iptables -t nat -A POSTROUTING -s "$LAN_NET" -o awg0 -j MASQUERADE

    # --- Policy Routing ---
    ipset create "$IPSET_NAME" hash:net maxelem 100000 comment 2>/dev/null || true

    # Routing Table
    ip route flush table "$WAN_TABLE"
    ip route add default via "$WAN_GW" dev "$WAN_IF" table "$WAN_TABLE"

    # IP Rules
    ip rule del fwmark "$FW_MARK" table "$WAN_TABLE" 2>/dev/null
    ip rule add fwmark "$FW_MARK" table "$WAN_TABLE"

    # Mark Traffic
    iptables -t mangle -C PREROUTING -m set --match-set "$IPSET_NAME" dst -j MARK --set-mark "$FW_MARK" 2>/dev/null || \
    iptables -t mangle -A PREROUTING -m set --match-set "$IPSET_NAME" dst -j MARK --set-mark "$FW_MARK"
    
    iptables -t mangle -C OUTPUT -m set --match-set "$IPSET_NAME" dst -j MARK --set-mark "$FW_MARK" 2>/dev/null || \
    iptables -t mangle -A OUTPUT -m set --match-set "$IPSET_NAME" dst -j MARK --set-mark "$FW_MARK"

    echo "Split routing applied."
}

remove_fw() {
    iptables -D FORWARD -i "$LAN_BR" -o awg0 -j ACCEPT 2>/dev/null
    iptables -D FORWARD -i awg0 -o "$LAN_BR" -j ACCEPT 2>/dev/null
    iptables -D INPUT -i awg0 -j ACCEPT 2>/dev/null
    iptables -t nat -D POSTROUTING -s "$LAN_NET" -o awg0 -j MASQUERADE 2>/dev/null

    iptables -t mangle -D PREROUTING -m set --match-set "$IPSET_NAME" dst -j MARK --set-mark "$FW_MARK" 2>/dev/null
    iptables -t mangle -D OUTPUT -m set --match-set "$IPSET_NAME" dst -j MARK --set-mark "$FW_MARK" 2>/dev/null
    
    ip rule del fwmark "$FW_MARK" table "$WAN_TABLE" 2>/dev/null
    ip route flush table "$WAN_TABLE" 2>/dev/null
}

cron_add() {
    [ ! -f "$WATCHDOG_SCRIPT" ] && return
    CRON_CMD="* * * * * sh $WATCHDOG_SCRIPT > /dev/null 2>&1"
    if ! crontab -l 2>/dev/null | grep -qF "awg_watchdog.sh"; then
        (crontab -l 2>/dev/null; echo "$CRON_CMD") | crontab -
    fi
}

cron_del() {
    if crontab -l 2>/dev/null | grep -qF "awg_watchdog.sh"; then
        crontab -l 2>/dev/null | grep -vF "awg_watchdog.sh" | crontab -
    fi
}

update_list() {
    echo "Forcing YouTube List Update..."
    if curl -s --connect-timeout 10 "$YT_URL" -o "$YT_CACHE"; then
        echo "Download successful."
        load_youtube_ips
    else
        echo "Download failed!"
    fi
}

up() {
    root
    if ip link show awg0 >/dev/null 2>&1; then
        echo "VPN is already UP."
        status
        exit 0
    fi

    echo "Starting VPN..."

    WG_SERVER=$(grep "^Endpoint" "$CFG" | sed 's/.*= *//' | cut -d':' -f1 | tr -d '\r')
    WG_ADDR=$(awk -F' = ' '/^Address/ {print $2}' "$CFG" | cut -d',' -f1 | tr -d '\r')
    awk '!/^Address/ && !/^DNS/' "$CFG" > "$IFCFG"
    
    [ -z "$WG_SERVER" ] || [ -z "$WG_ADDR" ] && die "Invalid config"

    save_wan_info || die "Could not detect WAN Gateway. Aborting."
    get_saved_wan 

    echo "Target Server: $WG_SERVER"

    pkill -f amneziawg-go 2>/dev/null
    [ -d /dev/net ] || mkdir -p /dev/net
    [ -c /dev/net/tun ] || mknod /dev/net/tun c 10 200
    
    export WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD=1
    $AWG_GO awg0 >/dev/null 2>&1 &
    
    count=0
    while ! ip link show awg0 >/dev/null 2>&1; do
        sleep 0.5
        count=$((count+1))
        [ $count -ge 10 ] && die "awg0 failed to create interface."
    done

    ip addr flush dev awg0 2>/dev/null
    ip addr add "$WG_ADDR" dev awg0
    "$TOOLS_BIN" setconf awg0 "$IFCFG"
    ip link set up awg0
    ip link set mtu 1280 dev awg0

    # 1. Create IPset and Load Static List
    load_youtube_ips
    # 2. Setup Dnsmasq to dynamically add IPs to the same set
    setup_dns_ipset

    ip route add "$WG_SERVER"/32 via "$WAN_GW" dev "$WAN_IF"
    ip route del default 2>/dev/null
    ip route add default dev awg0

    remove_fw
    apply_fw
    
    ip route flush cache
    cron_add
    /etc/init.d/firewall reload

    echo "VPN IS UP"
    echo -n "Public IP: "
    curl -s --max-time 5 ifconfig.me || echo "Check manually"
    echo
}

down() {
    echo "Stopping VPN..."
    root
    get_saved_wan 
    WG_SERVER=$(grep "^Endpoint" "$CFG" | sed 's/.*= *//' | cut -d':' -f1 | tr -d '\r')

    ip route del default dev awg0 2>/dev/null
    [ -n "$WG_SERVER" ] && ip route del "$WG_SERVER"/32 2>/dev/null
    
    if [ -n "$WAN_GW" ]; then
        echo "Restoring default route to $WAN_GW..."
        ip route del default 2>/dev/null
        ip route add default via "$WAN_GW" dev "$WAN_IF" 2>/dev/null
    else
        echo "Warning: No saved gateway. Restoring network..."
        /etc/init.d/network restart
    fi

    remove_fw
    remove_dns_ipset  # Remove dnsmasq rules
    
    [ -x "$(command -v conntrack)" ] && conntrack -F >/dev/null 2>&1
    
    ip link del awg0 2>/dev/null
    pkill -f amneziawg-go 2>/dev/null
    rm -f "$STATE_FILE" "$IFCFG" 2>/dev/null
    cron_del
    /etc/init.d/firewall reload

    echo "VPN IS DOWN"
}

status() {
    if ip link show awg0 >/dev/null 2>&1; then
        echo "VPN Status: [CONNECTED]"
        echo "Routing YouTube via: WAN"
        echo "Domain Sniffing: Active"
        # Check count of IPs
        echo "YouTube IP List: $(ipset list youtube | grep "Number of entries" | awk '{print $4}') entries active"
    else
        echo "VPN Status: [DISCONNECTED]"
    fi
}

case "$1" in
    up) up ;;
    down) down ;;
    status) status ;;
    update) update_list ;;
    restart) down; sleep 2; up ;;
    *) echo "Usage: $0 {up|down|status|update|restart}" ;;
esac
